### ISSUE TITLE
Use workflow to test inst hub config

### ISSUE THREAD

**Issue by annakrystalli** [hubverse-org/hubUtils#158]
Instead of validating `inst` test hub config as part of the test suite (and therefore imposing a `Suggests` dependency on `hubAdmin`), use config validation workflow developed in https://github.com/hubverse-org/hubverse-actions/pull/20.

**Comment by zkamvar** [comment]
I think that's a really good idea especially considering that these tests currently do not do anything to test any of the code inside {hubUtils}.
