### ISSUE TITLE
version equality functions (e.g. `version_lt()`) compare strings, not numbers. 

### ISSUE THREAD

**Issue by zkamvar** [hubverse-org/hubUtils#177]
I noticed an error in the version comparison functions implemented in #172.

If you test `"v3.0.11" < "v3.0.2"`, it the answer is `TRUE`, even though 11 is not less than 2:

``` r
# OK should be FALSE: 3.0.11 is not less than 3.0.1
hubUtils::version_lt("v3.0.1", schema_version = "v3.0.11")
#> [1] FALSE
# NOT OK should be FALSE: 3.0.11 is not less than 3.0.2
hubUtils::version_lt("v3.0.2", schema_version = "v3.0.11")
#> [1] TRUE
```

<sup>Created on 2024-10-21 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

The solution to this is to pass the version strings to `package_version()`

**Comment by annakrystalli** [comment]
Good catch ! We rarely deal with double digit version components but it's a bug non the less. Fixed in #178
