### ISSUE TITLE
Suggestion: use local directory cache to store schema versions

### ISSUE THREAD

**Issue by zkamvar** [hubverse-org/hubUtils#188]
Based on @annakrystalli's experience in https://github.com/hubverse-org/hubAdmin/pull/76, while we have schema memoized (e.g. https://github.com/hubverse-org/hubUtils/blob/9e45dedb421ed30bbf7a55910c942d036829948a/R/zzz.R#L9), these memoizations are only good for a single R session (which is independent from the test session).

Using [rappdirs](https://rappdirs.r-lib.org) to cache the config files on the user's local machine might help (but is not a replacement for validating the existence of online resources). I think we might even be able to register a drop-in replacement [using memoize's disk cache](https://memoise.r-lib.org/#caches):

```r
.onLoad <- function(libname, pkgname) {
  # Local hub config files use in-memory cache
  read_config.default <<- memoise::memoise(read_config.default)
  read_config.SubTreeFileSystem <<- memoise::memoise(read_config.SubTreeFileSystem)

  # schema should be stored in "hubUtils" directory inside of user-level cache directory
  cd <- cachem::cache_disk(rappdirs::user_cache_dir("hubUtils"))
  get_schema <<- memoise::memoise(get_schema, cache = cd)
  get_schema_valid_versions <<- memoise::memoise(get_schema_valid_versions, cache = cd)
}
```

The only catch would be actively testing new schema versions (like we are currently doing), but that is easily circumvented by [dropping the cache](https://memoise.r-lib.org/reference/drop_cache.html) for `get_schema` when the URL points to the version being tested:

```r
drop_schema_cache <- function(config = "tasks", version = "v4.0.0", branch = "br-v4.0.0") {
  url <- hubUtils::get_schema_url(config, version, branch)
  memoise::drop_cache(hubUtils::get_schema)(url)
}
```

**Comment by annakrystalli** [comment]
This feels like over-engineering to me to solve an extremely rare problem.

More specifically, I'm not keen on this for the following reasons:
1. Memoisation already poses a small risk of not using the most up to date version of a schema which becomes a much bigger problem when developing against an under development schema. I feel memoisation per session is the appropriate balance between not repeating the action and risking working with a superseded schema version and don't like the idea of having to remember to drop caches when developing.
2. I don't like the idea of writing to user's local systems, I don't think CRAN will either and don't feel any perceived benefit justifies the level of messaging/documentation/asking for consent by users we'll have to add to do this properly.
1. I'm actually having issues with the internet here and expecting engineers to come have a look so I don't think changing our package behaviour in response to this is necessary.

**Comment by zkamvar** [comment]
I'm okay letting this lie. I opened this not as a suggestion to immediately work on, but something to think of as a quality of life improvement for modelers and hub administrators. 

There are a couple of things I wanted to clarify below.

> I'm actually having issues with the internet here

This highlights the fact that we cannot always assume that users will have fast or good internet. It's an accessibility issue, ulitmately. People may be working off of their phones, or may be working off of a capped internet plan. Requiring constant internet access means that we put an extra burden (even if it's just a little) on people in areas that don't have reliable internet connections. 

> becomes a much bigger problem when developing against an under development schema

I addressed this with `memoise::drop_cache`.

> I don't like the idea of writing to user's local systems, I don't think CRAN will either 

Clarification: When R 4.0 was released in 2020, CRAN was very clear that the application directory is the one place where it's allowed: https://r-pkgs.org/data.html#sec-data-persistent

**Comment by annakrystalli** [comment]
If modelers are having internet issues, getting the tiny json schema file once in their session is the least of their worries tbh as pushing and pulling data which is the main purspose of the hub is a much bigger problem. 

Overall it helps very few people in the grand scheme of things but will make development more cumbersome. I really would prefer if we just decided not to do this.
